---
title: "About Me"
description: |
  My experience
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I'm originally from New York City and grew up surrounded by buildings sandwiched between Riverside Park and Central Park. My time exploring the urban jungle from one subway car to another was contrasted by the thousands of hours I spent rambling through Central Park's 843 acres of woods, meadows, and hills. In the winter I would spend winters in Vermont skiing in the mountains and learning how to tune skis at the local shop. Working in DC at an energy efficiency firm after college I spent a great deal of time in city's green spaces and increasingly more time hiking in the Appalachian mountains. Growing restless and with a drive to build new experiences I left DC and drove across the country, visiting 13 national parks along the way, and ended up in Telluride, Colorado where I worked as a ski instructor and remotely supported research for a startup company looking to establish best practices for decarbonization in the textile industry. 

My interest in the environmental field was inspired by my time exploring urban parks and admiring the mountains of Vermont, while my drive into the energy space was instigated by my senior capstone project in college. After reading a book on financing options for community scale renewable energy projects I was inspired to develop a proposal for anaerobic digestor on campus that would convert dining hall food waste to biogas that could be used at our on site boiler plant. Meanwhile, I also created a GIS model to identify the most suitable locations on campus for the implementation of solar panels in the first renewable energy project financed through Virginia's PPA pilot program. I later worked at Elysian Energy where I coordinated over 30 multifamily energy efficiency projects which saved residents millions in reduced energy usage and abated 5,000 tons of CO2. Now I am at the Bren school of Environmental Science and management where I am learning about the different variables and considerations that go into developing renewable energy projects at different scales.